export const createUISlice = (set, get) => ({
  clocks: { white: null, black: null },
  players: { white: 'Blancas', black: 'Negras' },
  arrows: [],
  highlights: {},
  gamePhase: 'Opening',
  openingName: 'Initial Position',
  importedGames: [],
  searchUsername: 'elcolof',
  searchPlatform: 'lichess',
  lichessToken: import.meta.env.VITE_TOKEN_LICHESS || '',
  boardOrientation: 'white',
  gameId: 0,

  setGameId: (id) => set({ gameId: id }),
  setBoardOrientation: (orientation) => set({ boardOrientation: orientation }),
  setArrows: (arrows) => set({ arrows }),
  setHighlights: (highlights) => set({ highlights }),
  setGamePhase: (phase) => set({ gamePhase: phase }),
  setOpeningName: (name) => set({ openingName: name }),
  setClocks: (white, black) => set({ clocks: { white, black } }),
  setPlayers: (white, black) => set({ players: { white, black } }),
  setImportedGames: (games) => set({ importedGames: games }),
  setSearchUsername: (username) => set({ searchUsername: username }),
  setSearchPlatform: (platform) => set({ searchPlatform: platform }),
  setLichessToken: (token) => set({ lichessToken: token }),
});
